resource "aws_route53_delegation_set" "name_servers" {
  // Group of 4 name servers, generated by AWS. These four values must be 
  // the same for both the hosted zone and the registered domain.
  reference_name = "WebsiteDNS"
}
