name: Deploy website

on:
  push:
    branches: ["main"]

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"

      - name: Install packages
        working-directory: astro
        run: npm install

      - name: Build
        working-directory: astro
        run: npm run build

      - name: Deploy
        run: ./scripts/deploy.sh
